server:
  port: 9999
spring:
  rabbitmq:
    host: 47.111.173.188
    port: 5672
    username: yfdev
    password: yfdev
    template:
      receive-timeout: 1200000
      reply-timeout: 1200000
  redis:
    host: 47.111.173.188
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    # 最大空闲数
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 200
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制） 默认 -1
        max-wait: 1000
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
      shutdown-timeout: 20000
fdfs:
  # 读取超时
  so-timeout: 100000
  # 连接超时
  connect-timeout: 100000
  tracker-list:
    - 47.111.173.188:22122
logging:
  file:
    name: C:\gramtu\logs\gramtu-rmq.log
